package team.unicon.ukrainemetro.localization

/**
 * Abstract class defining all the localizable strings available in the application.
 * All concrete language implementations will extend this.
 */
abstract class Strings {
    abstract val btnGooglePlay: LocalizedString
    abstract val btnGithub: LocalizedString
    abstract val btnResetCity: LocalizedString
    abstract val aboutText: LocalizedString
    abstract val close: LocalizedString
    abstract val labelSelectCity: LocalizedString
    abstract val btnNext: LocalizedString
    abstract val failureUnknown: LocalizedString
    abstract val failureMapNotSelected: LocalizedString
    abstract val actionSelect: LocalizedString

    abstract val cityKharkiv: LocalizedString
    abstract val cityKyiv: LocalizedString
    abstract val cityKryvyiRih: LocalizedString
    abstract val cityDnipro: LocalizedString

    abstract val namePeremoha: LocalizedString
    abstract val nameOleksiivska: LocalizedString
    abstract val name23Serpnia: LocalizedString
    abstract val nameBotanichnyiSad: LocalizedString
    abstract val nameNaukova: LocalizedString
    abstract val nameDerzhprom: LocalizedString
    abstract val nameArkhitektoraBeketova: LocalizedString
    abstract val nameZakhysnykivUkrainy: LocalizedString
    abstract val nameMetrobudivnykivKharkiv: LocalizedString
    abstract val nameKholodnaHora: LocalizedString
    abstract val namePivdennyiVokzal: LocalizedString
    abstract val nameTsentralnyiRynok: LocalizedString
    abstract val nameMaidanKonstytutsii: LocalizedString
    abstract val nameProspektHaharina: LocalizedString
    abstract val nameSportyvna: LocalizedString
    abstract val nameZavodskaKharkiv: LocalizedString
    abstract val nameTurboatom: LocalizedString
    abstract val namePalatsSportuKharkiv: LocalizedString
    abstract val nameArmiiska: LocalizedString
    abstract val nameImOSMaselskoho: LocalizedString
    abstract val nameTraktornyiZavod: LocalizedString
    abstract val nameIndustrialnaKharkiv: LocalizedString
    abstract val nameSaltivska: LocalizedString
    abstract val nameStudentska: LocalizedString
    abstract val nameAkademikaPavlova: LocalizedString
    abstract val nameAkademikaBarabashova: LocalizedString
    abstract val nameKyivska: LocalizedString
    abstract val namePushkinska: LocalizedString
    abstract val nameUniversytetKharkiv: LocalizedString
    abstract val nameIstorychnyiMuzei: LocalizedString

    abstract val nameAkademmistechko: LocalizedString
    abstract val nameZhytomyrska: LocalizedString
    abstract val nameSviatoshyn: LocalizedString
    abstract val nameNyvky: LocalizedString
    abstract val nameBeresteiska: LocalizedString
    abstract val nameShuliavska: LocalizedString
    abstract val namePolitekhnichnyiInstytut: LocalizedString
    abstract val nameVokzalnaKyiv: LocalizedString
    abstract val nameUniversytetKyiv: LocalizedString
    abstract val nameTeatralna: LocalizedString
    abstract val nameKhreshchatyk: LocalizedString
    abstract val nameArsenalna: LocalizedString
    abstract val nameDniproKyiv: LocalizedString
    abstract val nameHydropark: LocalizedString
    abstract val nameLivoberezhna: LocalizedString
    abstract val nameDarnytsia: LocalizedString
    abstract val nameChernihivska: LocalizedString
    abstract val nameLisova: LocalizedString
    abstract val nameHeroivDnipro: LocalizedString
    abstract val nameMinska: LocalizedString
    abstract val nameObolon: LocalizedString
    abstract val namePochaina: LocalizedString
    abstract val nameTarasShevchenko: LocalizedString
    abstract val nameKontraktovaPloshcha: LocalizedString
    abstract val namePoshtovaPloshcha: LocalizedString
    abstract val nameMaidanNezalezhnosti: LocalizedString
    abstract val namePloshchaUkrainskykhHeroiv: LocalizedString
    abstract val nameOlimpiiska: LocalizedString
    abstract val namePalatsUkraina: LocalizedString
    abstract val nameLybidska: LocalizedString
    abstract val nameDemiivska: LocalizedString
    abstract val nameHolosiivska: LocalizedString
    abstract val nameVasylkivska: LocalizedString
    abstract val nameVystavkovyiTsentr: LocalizedString
    abstract val nameIpodrom: LocalizedString
    abstract val nameTeremky: LocalizedString
    abstract val nameSyrets: LocalizedString
    abstract val nameDorohozhychi: LocalizedString
    abstract val nameLukianivska: LocalizedString
    abstract val nameZolotiVorota: LocalizedString
    abstract val namePalatsSportuKyiv: LocalizedString
    abstract val nameKlovska: LocalizedString
    abstract val namePecherska: LocalizedString
    abstract val nameZvirynetska: LocalizedString
    abstract val nameVydubychi: LocalizedString
    abstract val nameSlavutych: LocalizedString
    abstract val nameOsoborky: LocalizedString
    abstract val namePozniaky: LocalizedString
    abstract val nameKharkivskaKyiv: LocalizedString
    abstract val nameVyrlitsia: LocalizedString
    abstract val nameBoryspilska: LocalizedString
    abstract val nameChervonyiKhutir: LocalizedString

    abstract val nameZarichna: LocalizedString
    abstract val nameElektrozavodska: LocalizedString
    abstract val nameIndustrialnaKryvyiRih: LocalizedString
    abstract val nameSoniachna: LocalizedString
    abstract val nameMiskaLikarnia: LocalizedString
    abstract val nameVechirniiBulvar: LocalizedString
    abstract val nameMudryona: LocalizedString
    abstract val nameBudynokRad: LocalizedString
    abstract val nameProspektMetalurhiv: LocalizedString
    abstract val nameUniversytetKryvyiRih: LocalizedString
    abstract val nameVulytsiaVitchyzny: LocalizedString
    abstract val nameTretiuDilnytsia: LocalizedString
    abstract val nameKiltsevaAMKR: LocalizedString
    abstract val nameMaidanPratsi: LocalizedString
    abstract val nameKiltsevaKryvyiRih: LocalizedString

    abstract val namePokrovska: LocalizedString
    abstract val nameProspektSvobody: LocalizedString
    abstract val nameZavodskaDnipro: LocalizedString
    abstract val nameMetalurhivDnipro: LocalizedString
    abstract val nameMetrobudivnykivDnipro: LocalizedString
    abstract val nameVokzalnaDnipro: LocalizedString
}